version: '2.1'
#must be at least 2.1 to recognize default format {VAR:-default}
#http://github.com/ajdruff/docker-deck-pdns
#docker-compose up
############variable substitution########
#To set the variables within this file, edit .env or set using a shell script before running docker-compose.yml
############container environmental variables########
#(equivilent to docker run -e VARIABLE=VALUE)
#To set environmental variables in a service container,
#create a file service_name.env and place in the docker directory
#add an env_file definition under the service:
     #env_file:
     #    - docker/service-name.env
#alternately, you can simply use the 'environment' tag and assign values that are set in the .env file

#The  variable values that you see in this file  ,e.g: ${VAR_NAME} , are set in the local .env file
#variables (as opposed to variable values) that are set in this file are valid only within the container they associated with
#BUILD_VAR1 is only seen by the build script and not the containier
#MYSERVICE_ENV1 is only seen by the container 'myservice'

#

services:
   mysql:
    container_name: example.com_mysql
    image: mysql:5.7   
    #entrypoint: /usr/local/bin/docker-deck/entrypoint.sh       
    #command: /usr/local/bin/docker-deck/command.sh

    env_file: 
        - .docker/mysql/mysql.env 
    #additional container environmental variables not contained in env_file
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
        MYSQL_USER: ${WORDPRESS_DB_USER}
        MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes: 
    - ${DB_DATA_PATH:-mysql_data}:/var/lib/mysql
    ports:
        - ${MYSQL_PORT}:3306
    restart: "no"

   wordpress:
    depends_on:
      - mysql
    container_name: example.com_wp
    image: wordpress:latest    
    #entrypoint: /usr/local/bin/docker-deck/entrypoint.sh       
    #command: /usr/local/bin/docker-deck/command.sh

    env_file: 
        - .docker/wordpress/wordpress.env
    #additional container environmental variables not contained in env_file
    environment:
        WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
        WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
        WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"        
    volumes:
        - wp_html:/var/www/html
    ports:
        - ${WEBSERVER_PORT}:80

    restart: "no"
volumes: 
     wp_html:
     mysql_data:     